packages:
  - packages/*
overrides:
  '@gaurab-ui/button': link:C:/Users/paudy/AppData/Local/pnpm/global/5/node_modules/@gaurab-ui/button
  '@gaurab-ui/modal': link:C:/Users/paudy/AppData/Local/pnpm/global/5/node_modules/@gaurab-ui/modal
